# Generated by Django 4.2.5 on 2023-09-11 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 9, 11), verbose_name='дата старта рассылки'),
        ),
    ]
