# Generated by Django 4.2.5 on 2023-09-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата завершения рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('started', 'Активна'), ('created', 'Создана'), ('done', 'Неактивна')], default='created', max_length=20, verbose_name='статус рассылки'),
        ),
    ]
