# Generated by Django 4.2.5 on 2023-09-11 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailing_stop_date_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 9, 12), verbose_name='дата старта рассылки'),
        ),
    ]
