# Generated by Django 4.2.5 on 2023-09-11 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата старта рассылки'),
        ),
    ]
