# Generated by Django 4.2.5 on 2023-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='превью')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('published_at',),
            },
        ),
    ]
